version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scanfood-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - scanfood-network

networks:
  scanfood-network:
    driver: bridge
