import type { TemplateEvent, TemplateChannel } from './notif-template.types';

interface DefaultTemplate {
  title_template: string;
  body_template: string;
  html_template: string | null;
}

export const DEFAULT_TEMPLATES: Record<TemplateEvent, Record<TemplateChannel, DefaultTemplate>> = {
  NEW_ORDER: {
    dingtalk: {
      title_template: '\u{1F6CE} 新订单・{{tableLabel}}',
      body_template: [
        '### {{storeName}} · \u{1F6CE} **新订单**',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**金额**：¥**{{totalAmount}}**',
        '**下单时间**：{{createdAt}}',
        '',
        '**菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    wecom: {
      title_template: '\u{1F6CE} 新订单・{{tableLabel}}',
      body_template: [
        '### {{storeName}} · \u{1F6CE} **新订单**',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**金额**：¥**{{totalAmount}}**',
        '**下单时间**：{{createdAt}}',
        '',
        '**菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    feishu: {
      title_template: '\u{1F6CE} 新订单・{{tableLabel}}',
      body_template: [
        '**{{storeName}}** · \u{1F6CE} 新订单',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**金额**：¥{{totalAmount}}',
        '**下单时间**：{{createdAt}}',
        '',
        '**菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    email: {
      title_template: '【{{storeName}}】新订单 {{orderNumber}}（{{tableLabel}}）',
      body_template: [
        '亲爱的 {{recipientName}}，',
        '',
        '收到一笔新订单：',
        '',
        '订单号：{{orderNumber}}',
        '桌台：{{tableLabel}}',
        '总额：{{totalAmount}}',
        '菜品：',
        '{{itemsSummary}}',
        '下单时间：{{createdAt}}',
        '{{detailUrl}}',
        '',
        '—— {{storeName}} 通知服务',
      ].join('\n'),
      html_template: null,
    },
  },
  ADD_ITEM: {
    dingtalk: {
      title_template: '\u{1F372} 加菜・{{tableLabel}}',
      body_template: [
        '### {{storeName}} · \u{1F372} **订单加菜**',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**加菜金额**：¥**{{totalAmount}}**',
        '**下单时间**：{{createdAt}}',
        '',
        '**新加菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    wecom: {
      title_template: '\u{1F372} 加菜・{{tableLabel}}',
      body_template: [
        '### {{storeName}} · \u{1F372} **订单加菜**',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**加菜金额**：¥**{{totalAmount}}**',
        '**下单时间**：{{createdAt}}',
        '',
        '**新加菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    feishu: {
      title_template: '\u{1F372} 加菜・{{tableLabel}}',
      body_template: [
        '**{{storeName}}** · \u{1F372} 加菜',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**加菜金额**：{{totalAmount}}',
        '**下单时间**：{{createdAt}}',
        '',
        '**新加菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    email: {
      title_template: '【{{storeName}}】加菜通知 {{orderNumber}}（{{tableLabel}}）',
      body_template: [
        '亲爱的 {{recipientName}}，',
        '',
        '收到一笔加菜请求：',
        '',
        '订单号：{{orderNumber}}',
        '桌台：{{tableLabel}}',
        '加菜后总额：{{totalAmount}}',
        '新加菜品：',
        '{{itemsSummary}}',
        '下单时间：{{createdAt}}',
        '{{detailUrl}}',
        '',
        '—— {{storeName}} 通知服务',
      ].join('\n'),
      html_template: null,
    },
  },
  REFUND: {
    dingtalk: {
      title_template: '\u{1F4B8} 退款申请・{{tableLabel}}',
      body_template: [
        '### {{storeName}} · \u{1F4B8} **退款申请**',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**订单总额**：¥**{{totalAmount}}**',
        '**申请时间**：{{createdAt}}',
        '',
        '**订单菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    wecom: {
      title_template: '\u{1F4B8} 退款申请・{{tableLabel}}',
      body_template: [
        '### {{storeName}} · \u{1F4B8} **退款申请**',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**订单总额**：¥**{{totalAmount}}**',
        '**申请时间**：{{createdAt}}',
        '',
        '**订单菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    feishu: {
      title_template: '\u{1F4B8} 退款申请・{{tableLabel}}',
      body_template: [
        '**{{storeName}}** · \u{1F4B8} 退款申请',
        '',
        '**桌台**：{{tableLabel}}',
        '**订单号**：{{orderNumber}}',
        '**订单总额**：{{totalAmount}}',
        '**申请时间**：{{createdAt}}',
        '',
        '**订单菜品**：',
        '{{itemsSummary}}',
      ].join('\n'),
      html_template: null,
    },
    email: {
      title_template: '【{{storeName}}】退款申请 {{orderNumber}}（{{tableLabel}}）',
      body_template: [
        '亲爱的 {{recipientName}}，',
        '',
        '收到一笔退款申请：',
        '',
        '订单号：{{orderNumber}}',
        '桌台：{{tableLabel}}',
        '订单总额：{{totalAmount}}',
        '菜品：',
        '{{itemsSummary}}',
        '申请时间：{{createdAt}}',
        '{{detailUrl}}',
        '',
        '—— {{storeName}} 通知服务',
      ].join('\n'),
      html_template: null,
    },
  },
};
